### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Josnon** [Josnon/CalcAss#1]
### Tasks
##TODO list 
#DropDowns\Entry msg

#Button's main
- [ ] Display numbers and dot 
- [ ] operators(when on basic mode after eact operator use eval , in scie mode use math rules)(add to history)
- [ ] equal(diplay res on screen , add to history)
- [ ] back , reset (back:delete last digit , reset:clear screen & clear history)
- [ ] history,scientific(show/close)(history will save always the valuse(no matter if open or close))(scie:when open use math rules & accept scie buttons)
- [ ] dark/light mode(display screen color)
- [ ] about(info about Developers name , Calculators version , Description of this app)
- [ ] settings
  #setting button
  - [ ] Dropdown list , background color (list of 5 colors).
  - [ ] Dropdown list , font family (list of 5).
  - [ ] Dark/light mode
- [ ] cloud(outside API)(when clicked all the calculations will come from the API)
#Button's scientific
- [ ] power 2
- [ ] root 2
- [ ] power x
- [ ] root x
- [ ] pi
- [ ] mod
- [ ] base 2

#bonuses
[]add input for keybord(user can write expression through keybord)
[]add !,+/- operand's

#my ideas
[]Entry msg : Developers name , Calculators version , Description of this app 
[]dont leave empty btns
[]add random shape calc
[]add popup window for easy tracking
